name: release

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - LICENSE

permissions:
  contents: write
  packages: write
  id-token: write
  security-events: write

jobs:
  ci:
    uses: irondragonservices/.github/.github/workflows/image-release.yml@main
    with:
      version-arg: SQUID_VERSION
